<script setup lang="tsx">
import { CButton } from '@/components/button';
import { CEChart } from '@/components/echart';
import { CModalForm } from '@/components/form/modal';
import { EFormRuleType, EFormType, ETypeChart } from '@/enums';
import { IEditTable, IForm } from '@/interfaces';
import { IMCode, IMCodeType } from '@/interfaces/model';
import { SCrud } from '@/services';
import { formatDataChart } from '@/utils';

const sCrud = SCrud<IMCode, IMCodeType>('Code', 'CodeType');
</script>

<template>
  <div class="h-full pb-10">
    <CButton @click="() => sCrud.set({ isVisible: true })" :text="'Modal Form'" />
    <CModalForm
      :facade="sCrud"
      :title="() => 'Modal Form'"
      :columns="columns"
      @submit="({ value }) => console.log(value)"
    />
    <CEChart v-for="(item, index) in dataDefault" :key="index + 'chart'" :option="item" />
  </div>
</template>
<script lang="tsx">
const table: IEditTable = {
  fields: {
    columns: [
      { key: 'content' },
      { key: 'code' },
      {
        key: 'from',
        children: [{ key: 'from2', children: [{ key: 'totalFrom' }, { key: 'numberFrom' }] }],
      },
      {
        key: 'to',
        children: [{ key: 'to2', children: [{ key: 'totalTo' }, { key: 'numberTo' }] }],
      },
      { key: 'note' },
    ],
  },
  meta: [
    {
      field: 'content',
      name: 'Nội dung',
      fullName: 'Nội dung',
      type: 'title',
    },
    {
      field: 'code',
      name: 'Mã số',
      fullName: 'Mã số',
      type: 'title',
    },
    {
      field: 'from',
      name: 'Nơi tới',
      fullName: 'Nơi tới',
      type: 'title',
    },
    {
      field: 'from2',
      name: 'Nơi tới 2',
      fullName: 'Nơi tới 2',
      type: 'title',
    },
    {
      field: 'totalFrom',
      name: 'Tổng số hộ',
      fullName: 'Tổng số hộ tới',
      type: 'number',
    },
    {
      field: 'numberFrom',
      name: 'Số hộ DTTS',
      fullName: 'Số hộ DTTS tới',
      type: 'number',
    },
    {
      field: 'to',
      name: 'Nơi đi',
      fullName: 'Nơi đi',
      type: 'title',
    },
    {
      field: 'to2',
      name: 'Nơi đi 2',
      fullName: 'Nơi đi 2',
      type: 'title',
    },
    {
      field: 'totalTo',
      name: 'Tổng số hộ',
      fullName: 'Tổng số hộ đi',
      type: 'number',
    },
    {
      field: 'numberTo',
      name: 'Số hộ DTTS',
      fullName: 'Số hộ DTTS đi',
      type: 'number',
    },
    {
      field: 'note',
      name: 'Ghi chú',
      fullName: 'Ghi chú',
      type: 'text',
    },
  ],
  data: [
    {
      content: 'Tổng cả tỉnh',
      code: 'xx02',
      totalFrom: 27,
      numberFrom: 35,
      totalTo: 31,
      numberTo: 27,
      note: '',
      order: 1,
      level: 0,
      isSummary: true,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_SUMMARY.DISTRICT',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px; font-weight:bold;',
    },
    {
      content: 'Quận Ba Đình',
      code: 'yy',
      totalFrom: 8,
      numberFrom: 10,
      totalTo: 9,
      numberTo: 8,
      note: '',
      order: 2,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H001',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 8,
      numberFrom: 10,
      totalTo: 9,
      numberTo: 8,
      note: '',
      order: 3,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phúc Xá',
      code: 'T',
      totalFrom: 5,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 5,
      note: '',
      order: 4,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00001',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Trúc Bạch',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 5,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00004',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Vĩnh Phúc',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 6,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00006',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 8,
      numberFrom: 4,
      totalTo: 6,
      numberTo: 8,
      note: '',
      order: 7,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 8,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_DT01',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 9,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_DT02',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Hoàn Kiếm',
      code: 'yy',
      totalFrom: 9,
      numberFrom: 9,
      totalTo: 10,
      numberTo: 9,
      note: '',
      order: 10,
      level: 1,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H002',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 9,
      numberFrom: 9,
      totalTo: 10,
      numberTo: 9,
      note: '',
      order: 11,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phúc Tân',
      code: 'T',
      totalFrom: 4,
      numberFrom: 4,
      totalTo: 7,
      numberTo: 4,
      note: '',
      order: 12,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00037',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Đồng Xuân',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 13,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00040',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Hàng Ma',
      code: 'T',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 14,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00043',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 6,
      numberFrom: 6,
      totalTo: 8,
      numberTo: 6,
      note: '',
      order: 15,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 5,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 5,
      note: '',
      order: 16,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_DT01',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 17,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_DT02',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Tây Hồ',
      code: 'yy',
      totalFrom: 7,
      numberFrom: 9,
      totalTo: 8,
      numberTo: 7,
      note: '',
      order: 1,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H003',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 7,
      numberFrom: 9,
      totalTo: 8,
      numberTo: 7,
      note: '',
      order: 3,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phú Thượng',
      code: 'T',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 4,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00091',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Nhật Tân',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 5,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00094',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Tứ Liên',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 6,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00097',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 7,
      numberFrom: 3,
      totalTo: 5,
      numberTo: 7,
      note: '',
      order: 7,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 8,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_DT01',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 9,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_DT02',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Long Biên',
      code: 'yy',
      totalFrom: 6,
      numberFrom: 8,
      totalTo: 7,
      numberTo: 6,
      note: '',
      order: 10,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H004',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 6,
      numberFrom: 8,
      totalTo: 7,
      numberTo: 6,
      note: '',
      order: 11,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Thượng Thanh',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 12,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00115',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Ngọc Thụy',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 13,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00118',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Giang Biên',
      code: 'T',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 14,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00121',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 5,
      numberFrom: 5,
      totalTo: 7,
      numberTo: 5,
      note: '',
      order: 15,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 16,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_DT01',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 17,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_DT02',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
  ],
};

const dataDefault: any[] = [
  {
    type: ETypeChart.Area,
    title: 'Line Chart One',
    series: [
      {
        field: 'totalFrom',
        name: 'Tổng số hộ tới',
        value: [
          [0, 0],
          [1, 1.3488096893269022],
          [2, 0.870353404927271],
          [4, 0.2582374710442245],
          [5, 3.4992630153517794],
          [6, 10.165796338844878],
          [7, 19.435802797730613],
          [8, 29.247221696220688],
          [9, 36.900573657650156],
          [10, 39.941591483707086],
          [11, 37.022903312892616],
          [12, 28.44151963796814],
          [13, 16.152947095922325],
          [14, 3.238238801433192],
          [19, 4.091031098382733],
          [20, 12.759421640647318],
        ],
      },
    ],
  },
  {
    title: 'Ring Chart',
    type: ETypeChart.RingHalfDonut,
    series: [
      {
        data: [{ value: 30, name: 'Tổng số hộ tới', field: 'totalFrom' }],
      },
    ],
    category: ['Quận Ba Đình'],
  },
  formatDataChart({ obj: table, type: ETypeChart.Bar, title: 'Bar Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.StackedBar, title: 'Stacked Bar Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Pie, title: 'Pie Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Ring, title: 'Ring Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Line, title: 'Line Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Scatter, title: 'Scatter Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Bubble, title: 'Bubble Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Area, title: 'Area Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.StackedArea, title: 'Stacked Area Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.LineBar, title: 'Line Bar Chart' }),
  {
    type: ETypeChart.Line,
    title: 'Line Chart One',
    series: [
      {
        field: 'totalFrom',
        name: 'Tổng số hộ tới',
        value: [
          [0, 0],
          [1, 1.3488096893269022],
          [2, 0.870353404927271],
          [4, 0.2582374710442245],
          [5, 3.4992630153517794],
          [6, 10.165796338844878],
          [7, 19.435802797730613],
          [8, 29.247221696220688],
          [9, 36.900573657650156],
          [10, 39.941591483707086],
          [11, 37.022903312892616],
          [12, 28.44151963796814],
          [13, 16.152947095922325],
          [14, 3.238238801433192],
          [19, 4.091031098382733],
          [20, 12.759421640647318],
        ],
      },
    ],
  },
];

const columns: IForm[] = [
  {
    name: 'Switch',
    title: 'Switch',
    formItem: {
      col: 4,
      type: EFormType.Switch,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'Radio',
    title: 'Radio',
    formItem: {
      col: 4,
      type: EFormType.Radio,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        { label: 'Value 2', value: '2' },
      ],
    },
  },
  {
    name: 'Checkbox',
    title: 'Checkbox',
    formItem: {
      col: 4,
      type: EFormType.Checkbox,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        { label: 'Value 2', value: '2' },
      ],
    },
  },
  {
    name: 'DateRange',
    title: 'DateRange',
    formItem: {
      col: 4,
      type: EFormType.DateRange,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'Time',
    title: 'Time',
    formItem: {
      col: 4,
      type: EFormType.Time,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'TimeRange',
    title: 'TimeRange',
    formItem: {
      col: 4,
      type: EFormType.TimeRange,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'TreeSelect',
    title: 'TreeSelect',
    formItem: {
      col: 4,
      type: EFormType.TreeSelect,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        {
          label: 'Value 2',
          value: '2',
          children: [
            { label: 'Value 1', value: '3' },
            { label: 'Value 2', value: '4' },
          ],
        },
      ],
    },
  },

  {
    title: 'Addable Table',
    name: 'Addable',
    formItem: {
      type: EFormType.Addable,
      rules: [{ type: EFormRuleType.Required }],
      addable: {
        textAdd: 'Add item',
        onAdd: value => console.log(value),
        isTable: true,
        showRemove: value => {
          console.log(value);
          return true;
        },
        idCheck: true,
      },
      column: [
        {
          title: 'hours',
          name: 'hours',
          formItem: {
            rules: [{ type: EFormRuleType.Required }],
            type: EFormType.Number,
          },
        },
      ],
    },
  },
  {
    title: 'Addable',
    name: 'Addable 2',
    formItem: {
      type: EFormType.Addable,
      rules: [{ type: EFormRuleType.Required }],
      addable: {
        textAdd: 'Add item',
        onAdd: value => console.log(value),
        isTable: false,
        showRemove: value => {
          console.log(value);
          return true;
        },
        idCheck: true,
      },
      column: [
        {
          title: 'hours',
          name: 'hours',
          formItem: {
            rules: [{ type: EFormRuleType.Required }],
            type: EFormType.Number,
          },
        },
      ],
    },
  },
];
</script>
